services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory-order-sys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
